ccflags-y += -fpass-plugin=/home/lrk/llvm-tutor/build/lib/libFuncTimer.so

obj-$(CONFIG_SAMPLE_KERNEL_TRAMPOLINE_MOVE) += kernel_trampoline_move.o
kernel_trampoline_move-objs := ktm_core.o ktm_func.o ktm_move.o ktm_die.o
