# SPDX-License-Identifier: GPL-2.0-only
hw_break-y := hw_breakpoint.o \
                   hw_breakpoint_manage.o \
                   hw_breakpoint_proc.o \
                   hw_breakpoint_smp.o \
                   hw_breakpoint_until.o

obj-$(CONFIG_SAMPLE_HW_BREAKPOINT) += hw_break.o
obj-$(CONFIG_SAMPLE_HW_BREAKPOINT) += dbg_dump.o